# Configuración de archivos para releases de bintools
# Autor: Mauro Rosero Pérez
#
# Herramientas de gestión de secretos incluidas:
# - bw-send.sh: Envío seguro de archivos y texto mediante Bitwarden Send
# - bw-ghpersonal.sh: Obtención automática de tokens GitHub desde Bitwarden
# - git-tokens.py: Gestión de tokens Git usando keyring del sistema
# - docs/secrets.md: Documentación completa sobre gestión segura de secretos
#
# Herramientas de desarrollo incluidas:
# - odevs-install.sh: Instalador automático de odoodevs (entorno de desarrollo Odoo)
# - docs/odoodevs.md: Documentación completa de odoodevs
# - docs/cursor-sync-guide.md: Guía para sincronizar contexto de Cursor con Nextcloud
# - docs/developers.md: Guía completa para desarrolladores
# - docs/documentation-guide.md: Guía para contribuir con documentación
# - docs/testing-guide.md: Guía de testing ágil
# - docs/packages.md: Guía completa de packages.sh
# - docs/pymanager.md: Guía completa de pymanager.sh
# - docs/repo.md: Guía completa de repo-install.sh
# - docs/bw-send.md: Guía completa de bw-send.sh

# Archivos principales que se incluyen en todos los releases
main_files:
  - packages.sh
  - micursor.py
  - pymanager.sh
  - fix_hdmi_audio.sh
  - videoset.sh
  - nxcloud-backup.sh
  - hexroute
  - bintools-manager.sh
  - git-tokens.py
  - bw-send.sh
  - bw-ghpersonal.sh
  - repo-install.sh
  - odevs-install.sh
  - pritunl-vpn.py

# Directorios que se incluyen completos
directories:
  - configs
  - repos
  - docs

# Archivos de configuración del proyecto
config_files:
  - VERSION
  - RELEASE_INFO

# Archivos opcionales que se pueden incluir según el tipo de release
optional_files:
  # Archivos de documentación
  documentation:
    - README.md
    - LICENSE
    - CHANGELOG.md
    - docs/secrets.md
    - docs/odoodevs.md
    - docs/cursor-sync-guide.md
    - docs/developers.md
    - docs/documentation-guide.md
    - docs/testing-guide.md
    - docs/packages.md
    - docs/pymanager.md
    - docs/repo.md
    - docs/bw-send.md
  
  # Herramientas de gestión de secretos
  secrets_tools:
    - bw-send.sh
    - bw-ghpersonal.sh
    - git-tokens.py
  
  # Archivos de desarrollo
  development:
    - .gitignore
    - docs/RELEASE.md
    - create-release.sh
    - delete-release.sh
    - release-builder.sh
    - btfixperms.sh
  
  # Archivos de configuración del proyecto
  project_config:
    - configs/release-config.yml

# Configuración por tipo de release
release_types:
  # Release completo (incluye todo)
  full:
    include_main: true
    include_directories: true
    include_config: true
    include_optional:
      - documentation
      - secrets_tools
      - development
      - project_config
  
  # Release de usuario (solo lo necesario para usar)
  user:
    include_main: true
    include_directories: true
    include_config: true
    include_optional:
      - documentation
      - secrets_tools
  
  # Release mínimo (solo archivos principales)
  minimal:
    include_main: true
    include_directories: true
    include_config: true
    include_optional:
      - secrets_tools

# Configuración por defecto
default_release_type: "user"

# Patrones de exclusión (archivos que nunca se incluyen)
exclude_patterns:
  - "*.tmp"
  - "*.log"
  - ".DS_Store"
  - "Thumbs.db"
  - "*.swp"
  - "*.swo"
  - "*~"
  - ".env"
  - "*.key"
  - "*.pem"
  - "*.p12"
